### ISSUE TITLE
Criterion 1 and Overall Feedback Issues

### ISSUE THREAD

**Issue by carlicockrell** [lucisgit/moodle-assignfeedback_structured#4]
I am providing this feedback on behalf of a client. The client is being provided a link to this comment in order to provide more details as necessary.

- The Structured feedback plugin allows for multiple criteria to be named, and qualitative feedback provided for each criterion
- No field for entering qualitative feedback exists in grading screens unless a criterion name has been defined, however
- Setting the field name of Criterion 1 to be “Overall Feedback” by default would mean professors save time upon Assignment creation and have an easy-to-use place to provide qualitative feedback
-  In our particular Moodle instance, we have set this plugin to be the one plugin that the Gradebook looks to for feedback on Assignments

**Comment by JosephKennedy4** [comment]
Thank you @carlicockrell .  I'm the client!  Please feel free to reach out if more information is needed.

**Comment by tonyjbutler** [comment]
Hi folks. Is this a feature request?

For the specific use case described here I would suggest the use of the 'Feedback comments' plugin (assignfeedback_comments) instead. It is built into Moodle out of the box, is enabled by default for all assignments, and provides a rich text editor for overall feedback without any additional configuration.

Or is there a wider issue that I'm missing?

Thanks, Tony

**Comment by JosephKennedy4** [comment]
Because the Gradebook plugin will only allow one feedback plugin to send information for display within the Gradebook, we must choose one or the other to be visible next to the "grade."  Our faculty would like to have the Structured Feedback be that tool, because it allows for more efficient feedback.  Since the Structured Feedback tool relies on a value being input in "Criterion 1" to make an entry box available when grading, some faculty members don't see any way to provide feedback that will show in the Gradebook.
Obviously, there is agency here - faculty members can enter a descriptor when creating the Assignment.  We work with them to provide this information.  However, if the field was auto-populated with a descriptor such as "Overall Feedback" when an Assignment is created, 
a) faculty members who just want to leave general feedback that is visible in the Gradebook can easily do so,
b) new faculty members and faculty members who struggle with tools like Moodle will have the mechanism already set up,
c) the faculty members who want the power of Structured Feedback as a mechanism for getting comments in front of student eyeballs will have their mechanism.

If it is **not** easy to have this field's value preset, then educating our faculty members will be the best path forward, but if the next release of the plugin _can_ easily include this feature, that would be more efficient.

**Comment by tonyjbutler** [comment]
Thanks Joseph, that makes perfect sense. It should be reasonably straightforward to build in support for a sitewide default name for the first criterion, which I'm thinking would be empty by default but configurable by the site admin. Does that sound like it would work for you?

I'm due to start working on a new feature for this plugin in the next couple of weeks anyway, so I'll include this as part of that work.

**Comment by JosephKennedy4** [comment]
Tony, that option (side admin configurable) sounds like a perfect solution - it's flexible by site, can still be overridden by individual instructors as needed, and would trigger the Assignment module into including the Structured Feedback field(s) in grading!

**Comment by JosephKennedy4** [comment]
Is there any assistance I can offer, or is there a date it would be appropriate to check back regarding this?

**Comment by tonyjbutler** [comment]
Sorry Joseph, other work priorities have been getting in the way of this, but it's still on my to-do list to get it done before our major upgrade in July. I'll update this issue when it's done so you should get a notification.

**Comment by tonyjbutler** [comment]
Hi Joseph, I've finally had a chance to look at this and it's actually pretty straightforward. Are you able to test the new commit that I've added to the master branch or do you need me to do a release first?

**Comment by JosephKennedy4** [comment]
I'd love to test the commit but I'll have to put that through our vendor/host - I'll let you know the timetable as soon as I know!  And thank you.  I'm glad it was pretty straightforward.

**Comment by JosephKennedy4** [comment]
@tonyjbutler :  we are in the middle of solving a thorny upgrade issue, but I should be able to test this by Monday 12JUN.

**Comment by JosephKennedy4** [comment]
@tonyjbutler :  I'm afraid I have only one way to test this code; we've been informed that any code changes will be propagated through the production site, and cannot be made just to the sandbox server.  If you're comfortable with the stability of the code, I will test this in our sites; please let me know.

**Comment by tonyjbutler** [comment]
@JosephKennedy4 I'm confident enough that the code isn't buggy, the testing was just to make sure it fitted your requirements.

Not to worry, I'll just release it as is. What version of Moodle are you running?

**Comment by JosephKennedy4** [comment]
We are using 4.0 and switching to 4.1 on August 4, but 4.0 for now.  Thank you - we'll get this installed next Tuesday* (which I assume Moodle US will modify for the July 4 holiday) when all the plugin upgrades happen, and I'll get back to you as soon as we see it in action!

**Comment by tonyjbutler** [comment]
If this is working for you I'll close the issue @JosephKennedy4

**Comment by JosephKennedy4** [comment]
This works beautifully; thank you @tonyjbutler .
For those wondering how to set, choose something like "Holistic Feedback" for the field described as "Default name for first criterion" and then provide a meaningful description in the field described as "Default description for first criterion," such as "Enter holistic feedback OR change the name of this first criterion and create multiple criteria so you can easily provide qualitative feedback using consistent terminology".  Doing so auto-activates the structured feedback method for all new assignmetns.

**Comment by tonyjbutler** [comment]
That's great to hear. Thanks Joseph.
